name: Discord Notification Workflow

on:
  issues:
    types:
      - opened

jobs:
  notify_on_discord:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Notification
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"content": "New issue opened: ${{ github.event.issue.title }}"}' ${{ secrets.DISCORD_WEBHOOK_URL }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
